/**
 * Action generated by user
 */
export interface IAction<T> {
  /** Type of action */
  type: string;
  /** Data passed with action */
  payload: T;
}

/* Payload interfaces */

export interface ItemPayload {
  item: IListItemData;
}

export interface IdPayload {
  id: string;
}

/* Models */

/**
 * List Item Data Model
 */
export interface IListItemData {
  /** Id of item */
  id: string;
  /** Value held by item */
  value: string;
}

/**
 * List Item Flags Model
 */
export interface IListItemFlags {
  /** Shows whether item is opened for editation */
  isBeingEdited: boolean;
}
/**
 * Merged Item data with Flags
 */
export interface IItemViewModel {
  /** Guid of item */
  guid: string;
  /** Value held by item */
  value: string;
  /** Shows whether item is opened for editation */
  isBeingEdited: boolean;
}
