/**
 * Action generated by user
 */
import { HttpActionStatus } from '../constants/HttpActionStatus';

export interface IAction {
  /** Type of action */
  type: string;
  /** Status of http action */
  status?: HttpActionStatus;
  /** Data passed with action */
  payload: any;
}
