/**
 * Action generated by user
 */
import { EHttpActionStatus } from '../constants/actionTypes';

export interface IAction {
  /** Type of action */
  type: string;
  /** Status of http action */
  status?: EHttpActionStatus;
  /** Data passed with action */
  payload: any;
}
